name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest \
          /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: jekyll-site
        path: _site/
        retention-days: 5
